# Generated by Django 3.2 on 2021-05-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote_value',
            field=models.SmallIntegerField(choices=[(None, '(Unknown)'), (-1, 'Downvote'), (1, 'Upvote')]),
        ),
    ]
